# feeder
# work_dir: ./work_dir/utd/agcn_joint
# model_saved_name: ./runs/utd_agcn_joint

feeder: Feeder.feeder.Feeder
dataset: 'utd'
train_feeder_args:
  data_path: /home/bgu9/2s-AGCN/data/utd_processed/train/train_data_joint.npy
  label_path: /home/bgu9/2s-AGCN/data/utd_processed/train/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 100
  normalization: False

val_feeder_args:
  data_path: /home/bgu9/2s-AGCN/data/utd_processed/test/test_data_joint.npy
  label_path: /home/bgu9/2s-AGCN/data/utd_processed/test/test_label.pkl

test_feeder_args:
  data_path: /home/bgu9/2s-AGCN/data/utd_processed/test/test_data_joint.npy
  label_path: /home/bgu9/2s-AGCN/data/utd_processed/test/test_label.pkl

# model
model: Models.agcn.Model
model_args:
  num_class: 27
  num_point: 20
  num_person: 1
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: 'spatial'


#optim
weight_decay: 0.0001
base_lr: 0.1
#step: [30, 40]

# training
device: 7
batch_size: 16
test_batch_size: 16
num_epoch: 100
#nesterov: True

seed: 2 