#Model
model: Models.model_acc_only.ActTransformerAcc
# file name of weights 
#work_dir: exps/UTD_woKD/acc_modal

model_args:
  acc_frames : 64
  num_joints : 25 
  num_classes : 20
  acc_embed : 64
  adepth : 2
  num_heads : 2
  acc_coords: 6
  # mocap_frames: 50


batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 700

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: sgd
