#Model
model: Models.ef_w_decoder.MMTransformer
model_saved_name : no_kd_aug_sw

#model_args
model_args:
  acc_frames : 128
  num_joints : 25
  num_classes : 27
  spatial_embed : 64
  adepth : 2
  sdepth : 2
  num_heads : 4
  mocap_frames: 32
  num_patch: 8
  acc_coords: 6


#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 32
test_batch_size: 32
val_batch_size : 32
num_epoch: 40

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 32

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 32

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 32

seed: 2 
optimizer: Adam
