#Model
model: Models.earlyfusion.MMTransformer

#model_args
model_args:
  acc_frames : 150
  num_joints : 25 
  num_classes : 27
  spatial_embed : 32 
  adepth : 4
  sdepth : 4
  num_heads : 8
  mocap_frames: 50


#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 200

#dataloader
feeder: Make_Dataset.UTD_mm

train_feeder_args:
  npz_file: data/UTD_MAAD/utd_train_op_mf50_acc150.npz
  batch_size: 16

val_feeder_args:
  npz_file: data/UTD_MAAD/utd_val_op_mf50_acc150.npz
  batch_size: 16

test_feeder_args: 
  npz_file: data/UTD_MAAD/utd_test_op_mf50_acc150.npz
  batch_size: 16

seed: 2 
optimizer: Adam