#Model
model: Models.st_cvtransformer.MMTransformer
# model : Models.model_crossview_fusion.ActRecogTransformer
# model_saved_name : tokenfusion_AdamW_avgpool
# work_dir: exps/UTD_woKD/with_AdamW
dataset: 'utd'


model_args:
  acc_frames : 64
  num_joints : 20
  num_classes : 27
  spatial_embed : 64
  adepth : 2
  sdepth : 2
  num_heads : 2
  mocap_frames: 32
  num_patch: 8
  acc_coords: 6 
  drop_path_rate: 0.4
  drop_rate: 0.4
  attn_drop_rate: 0.4

# model_args:
#   acc_frames : 64
#   num_joints : 20
#   num_classes : 27
#   spatial_embed : 32
#   adepth : 2
#   sdepth : 2
#   num_heads : 4
#   mocap_frames: 64
#   num_patch: 8
#   acc_coords: 6 
#   drop_path_rate: 0.4
#   drop_rate: 0.4
#   attn_drop_rate: 0.4

  # acc_embed: 16

# loss_args 
loss_args:
  beta: 0.2


#optim
weight_decay: 0.0004
# base_lr: 0.001


# training
batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 700

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: sgd
