model: Models.fusion_transformer.FusionTransModel
dataset: smartfallmm
subjects: [32, 39, 30, 31, 33, 34, 35, 37, 43, 44, 45, 36, 29]
val_subjects: [38, 46]
permanent_train: [45, 36, 29]
test_batch_size: 16
kfold: true
rotate_tests: true

model_args:
  num_layers: 3
  embed_dim: 36
  acc_coords: 3
  quat_coords: 4
  num_classes: 2
  acc_frames: 128
  mocap_frames: 128
  num_heads: 2
  fusion_type: 'concat'
  dropout: 0.3
  use_batch_norm: true
  feature_dim: 108

dataset_args:
  mode: 'sliding_window'
  max_length: 128
  task: 'fd'
  modalities: ['accelerometer', 'gyroscope']
  age_group: ['young']
  sensors: ['watch']
  fusion_options:
    enabled: true
    filter_type: 'kalman'
    process_per_window: true
    preserve_filter_state: true
    process_noise: 2e-5
    measurement_noise: 0.1
    acc_threshold: 3.0
    gyro_threshold: 1.0
    use_cache: false
    visualize: false
    save_aligned: true

batch_size: 16
val_batch_size: 16
num_epoch: 100
num_folds: 5

feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16
  drop_last: true

val_feeder_args:
  batch_size: 16
  drop_last: true

test_feeder_args:
  batch_size: 16
  drop_last: false

seed: 42
optimizer: adamw
base_lr: 0.0005
weight_decay: 0.001
patience: 15
