model: Models.transformer.TransModel
dataset: smartfallmm

# Fall detection subjects
subjects: [29,30,31,33,45,46,34,37,39,38,43,35,36,44,34,32]
model_args:
  num_layers: 2
  norm_first: True
  embed_dim: 24
  activation: gelu
  acc_coords: 3
  num_classes: 2
  acc_frames: 64
  mocap_frames: 64
  num_heads: 4
  dropout: 0.3

dataset_args: 
  mode: 'sliding_window'
  max_length: 64
  task: 'fd'
  modalities: ['accelerometer']
  age_group: ['young']
  sensors: ['watch']

batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 40

# dataloader
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16

val_feeder_args:
  batch_size: 16

test_feeder_args: 
  batch_size: 16

seed: 2 
optimizer: adam
base_lr: 0.0005
weight_decay: 0.001
