# Model configuration
model: Models.transformer.FallDetectionStudentModel
dataset: smartfallmm

subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

model_args:
  acc_coords: 4           # x, y, z, smv for accelerometer data
  seq_length: 128         # Length of the sequence
  embedding_dim: 32       # Changed from 64 to 32
  num_heads: 2            # Changed from 4 to 2
  num_layers: 2           # Changed from 4 to 2
  dim_feedforward: 32     # Changed from 128 to 32
  num_classes: 2          # Binary classification (fall vs no fall)
  dropout: 0.5            # Changed from 0.1 to 0.5

# Dataset arguments
dataset_args:
  mode: 'avg_pool'
  max_length: 128
  task: 'fd'             # Fall detection task
  modalities: ['accelerometer']
  age_group: ['young', 'old']
  sensors: ['phone']

# Training parameters
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 300
start_epoch: 0

feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16
val_feeder_args:
  batch_size: 16
test_feeder_args:
  batch_size: 16

# Optimization parameters
seed: 2
optimizer: 'sgd'
base_lr: 0.001

# Additional settings
work_dir: 'exps/smartfall_har/accel_only'
model_saved_name: 'accel_fall_detector'
print_log: True
phase: 'train'
num_worker: 0

# Device setting
device: [0]
