model: "Models.aMaxOp.FallDetectionModel"

# Model arguments
model_args:
  seq_len: 128          # Sequence length of the input data
  num_channels: 3       # Number of input channels per modality (x, y, z)
  num_filters: 128       # Number of filters in the CNN layers

# Dataset configuration
dataset: "smartfallmm"
subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

dataset_args:
  root_dir: "data/smartfallmm"
  age_groups:
    - "young"
    - "old"
  modalities:
    - "accelerometer"
  sensors:
    accelerometer:
      - "phone"
      - "watch"
  mode: "avg_pool"
  max_length: 128
  task: "fd"            # Task: Fall Detection
  use_smv: false        # Option to use SMV, currently disabled

# DataLoader configuration
feeder: "Feeder.Make_Dataset.UTD_mm"
train_feeder_args:
  batch_size: 32

val_feeder_args:
  batch_size: 32

test_feeder_args:
  batch_size: 32

# Training parameters
batch_size: 32
test_batch_size: 32
val_batch_size: 32
num_epoch: 75
start_epoch: 0

# Optimizer settings
optimizer: "adamw"
base_lr: 0.0001  # Reduced from 0.001 for more stable training with movement-aware loss
weight_decay: 0.0004

# Loss function
loss: "torch.nn.BCEWithLogitsLoss"
loss_args: {}

# Device setting
device: [0]

# System settings
include_val: True
seed: 2
log_interval: 10
work_dir: "exps/smartfall_har/fall_detection_model"
print_log: True
phase: "train"
num_worker: 0
result_file: results1
