#Model
teacher_model: Models.st_cvtransformer.MMTransformer
student_model: Models.model_acc_only.ActTransformerAcc

#teacher_weight: exps/UTD_woKD/MMNorm/convTransformer.pt
dataset: 'smartfallmm'
#model_args
teacher_args:
  acc_frames : 64
  num_joints : 32
  num_classes : 2
  spatial_embed : 64
  adepth : 2
  sdepth : 2
  num_heads : 2
  mocap_frames: 32
  num_patch: 8
  acc_coords: 3
  drop_path_rate: 0.4
  drop_rate: 0.4
  attn_drop_rate: 0.4

student_args: 
  acc_frames : 64
  num_joints : 32 
  num_classes : 2
  acc_embed : 64
  adepth : 2
  num_heads : 2
  acc_coords: 3

#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 2



#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

distill_loss: loss.SemanticLoss
distill_args: 
  T : 2
  alpha: 0.7

student_loss: loss.BCE


train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 8

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 8

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 8

seed: 2 
optimizer: sgd
