# Basic Configuration
student_model: "Models.StudentModel.StudentModel"
dataset: "smartfallmm"
phase: "test"  # Set to test for evaluation

# Model Configuration
student_args:
  input_channels: 4
  hidden_dim: 128
  num_blocks: 4
  dropout_rate: 0.2

# Dataset Configuration
dataset_args:
  modalities: ['watch']
  data_path: "data/smartfallmm"
  subjects: [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 44, 45, 46]

# Data Loading
feeder: "utils.feeder.smartfallmm.Feeder"
train_feeder_args:
  debug: False
  window_size: 128
  p_interval: [0.95]
  vel: False

val_feeder_args:
  debug: False
  window_size: 128
  p_interval: [0.95]
  vel: False

# Device Configuration
device: [0]
batch_size: 32
test_batch_size: 32
num_worker: 4

# Add path to your best model weights
weights: "work_dir/your_experiment/fold_1/best_f1_model_fold1.pt"  # Update this path
