model: Models.lightweight_student.LightweightStudent
dataset: smartfallmm

subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

model_args:
  num_layers: 2
  norm_first: True
  embed_dim: 32
  activation: 'gelu'
  acc_coords: 4
  num_classes: 2
  acc_frames: 128
  mocap_frames: 128
  num_heads: 2
  dropout: 0.4

# Dataset arguments
dataset_args:
  mode: 'avg_pool'
  max_length: 128
  task: 'fd'
  modalities: ['accelerometer']
  age_group: ['young', 'old']
  sensors: ['watch']

# Training parameters
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 100
start_epoch: 0

# Loss function
loss: 'torch.nn.CrossEntropyLoss'
loss_args: {}

# Data loader configuration
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16
val_feeder_args:
  batch_size: 16
test_feeder_args:
  batch_size: 16

# Device configuration
device: [0]

# Optimization parameters
seed: 2
optimizer: 'adamw'
base_lr: 0.0001
weight_decay: 0.01

# Model weights
weights: 'exps/smartfall_har/kd/student/watchgyro_divid3bw20/lightweight_student_latest.pth'

# Additional settings
work_dir: 'exps/smartfall_har/finetune/watch_acc_only'
model_saved_name: 'finetuned_fall_detector'
print_log: True
phase: 'train'
num_worker: 0
result_file: null

# Validation setting
include_val: True
log_interval: 10
