# config/smartfallmm/fusion.yaml
model: Models.fusion_transformer.FusionTransModel
dataset: smartfallmm

# Fall detection subjects
subjects: [29,30,31,33,45,46,34,37,39,38,43,35,36,44,34,32]

model_args:
  num_layers: 2
  embed_dim: 32
  acc_coords: 3
  quat_coords: 4
  num_classes: 2
  acc_frames: 64   # Match this with dataset_args.max_length
  mocap_frames: 64
  num_heads: 4
  fusion_type: 'concat'  # Options: 'concat', 'attention', 'weighted'
  dropout: 0.3
  use_batch_norm: true

dataset_args: 
  mode: 'sliding_window'
  max_length: 64    # Make sure this matches acc_frames
  task: 'fd'
  modalities: ['accelerometer', 'gyroscope']
  age_group: ['young']
  sensors: ['watch']
  fusion_options:
    enabled: true
    filter_type: "ekf"  # Options: madgwick, comp, kalman, ekf, ukf
    visualize: false    # Disable visualizations by default

batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 40

# dataloader
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16
  drop_last: true

val_feeder_args:
  batch_size: 16
  drop_last: true

test_feeder_args: 
  batch_size: 16
  drop_last: false

seed: 42
optimizer: adam
base_lr: 0.0005
weight_decay: 0.001
