# mms4.yaml

# Model configuration
model: Models.mms4.MultiModalStudentModel

# Model arguments
model_args:
  acc_coords: 4              # x, y, z, SMV
  spatial_embed: 256         # Embedding size for spatial data
  num_heads: 8               # Number of attention heads
  depth: 8                   # Depth of the transformer
  mlp_ratio: 4               # Ratio for the MLP head
  num_classes: 2             # Number of output classes
  dropout: 0.2               # Dropout rate

# Dataset configuration
dataset: smartfallmm

subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

dataset_args:
  root_dir: 'data/smartfallmm'   # Root directory for dataset
  age_group:                     # Age groups to include
    - 'young'
    - 'old'
  modalities:                    # Modalities to use
    - 'accelerometer'
  sensors:                       # Sensors for accelerometer modality
    accelerometer: 
      - 'watch'
      - 'phone'
  mode: 'avg_pool'               # Processing mode
  max_length: 128                # Maximum sequence length
  task: 'fd'                     # Task type (e.g., 'fd' for fall detection)

# DataLoader configuration
feeder: Feeder.Make_Dataset.UTD_mm  # Data feeder class
train_feeder_args:
  batch_size: 32                  # Batch size for training

val_feeder_args:
  batch_size: 32                  # Batch size for validation

test_feeder_args:
  batch_size: 32                  # Batch size for testing

# Training parameters
batch_size: 32                    # Default batch size
test_batch_size: 32               # Batch size for testing
val_batch_size: 32                # Batch size for validation
num_epoch: 150                    # Number of training epochs
start_epoch: 0                    # Starting epoch for training

# Optimizer configuration
optimizer: 'adamw'                # Optimizer type
base_lr: 0.0001                   # Base learning rate
weight_decay: 0.0004              # Weight decay for regularization

# Loss function
loss: 'CrossEntropyLoss'          # Loss function
loss_args: '{}'                   # Additional arguments for the loss function

# Training settings
work_dir: 'exps/smartfall_har/student'  # Directory to save checkpoints
model_saved_name: 'fall_detector_student'  # Name for the saved model
print_log: True                   # Print logs during training
phase: 'train'                    # Phase (e.g., 'train', 'test')
num_worker: 4                     # Number of workers for data loading

# Device setting
device: [0]                       # GPU device IDs to use

# Additional settings
seed: 2                           # Random seed for reproducibility
log_interval: 10                  # Interval for logging training progress
include_val: True                 # Include validation during training
