model: Models.mmt4.MultiModalTeacherModel
dataset: smartfallmm

# Model args
model_args:
  num_joints: 32
  in_chans: 3
  acc_coords: 4  # x, y, z
  spatial_embed: 256
  num_heads: 8
  depth: 8
  mlp_ratio: 4
  num_classes: 2
  dropout: 0.2

# Dataset configuration
subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

dataset_args:
  root_dir: 'data/smartfallmm'
  age_group: ['young', 'old']
  modalities: ['accelerometer', 'skeleton']
  sensors:
    accelerometer: ['watch', 'phone']
  mode: 'train'
  max_length: 128
  task: 'fd'

# DataLoader configuration
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 32

val_feeder_args:
  batch_size: 32

test_feeder_args:
  batch_size: 32

# Training parameters
batch_size: 32
test_batch_size: 32
val_batch_size: 32
num_epoch: 300
start_epoch: 0

# Optimizer configuration
optimizer: 'adamw'
base_lr: 0.0001
weight_decay: 0.004

# Loss function
loss: 'CrossEntropyLoss'
loss_args: '{}'

# Training settings
work_dir: 'exps/smartfall_har/kd/teacher'
model_saved_name: 'kdTransformer_accelerometer_teacher'
print_log: True
phase: 'train'
num_worker: 4

# Device setting
device: [0]

# Additional settings
seed: 2
log_interval: 10
include_val: True
