model: "models.mobile.MobileFallDetector"

# Model arguments
model_args:
  acc_coords: 4
  sequence_length: 128
  hidden_dim: 64
  num_heads: 4
  depth: 3
  mlp_ratio: 2
  num_classes: 2
  dropout: 0.2
  use_skeleton: false

# Dataset configuration
dataset: "smartfallmm"

subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

dataset_args:
  root_dir: "data/smartfallmm"
  age_groups: 
    - "young"
    - "old"
  modalities:
    - "accelerometer"
  sensors:
    accelerometer:
      - "phone"
      - "watch"
  mode: "avg_pool"
  max_length: 128
  task: "fd"

# DataLoader configuration
feeder: "feeder.make_dataset.UTD_mm"
train_feeder_args:
  batch_size: 32
  shuffle: true

val_feeder_args:
  batch_size: 32
  shuffle: false

test_feeder_args:
  batch_size: 32
  shuffle: false

# Training parameters
batch_size: 32
test_batch_size: 32
val_batch_size: 32
num_epoch: 100  # Reduced from 200 for faster convergence
start_epoch: 0

# Optimizer configuration
optimizer: "adamw"
base_lr: 0.001  # Slightly increased for faster convergence
weight_decay: 0.0001  # Reduced to prevent overfitting

# Loss function
loss: "torch.nn.CrossEntropyLoss"
loss_args: {}

# Device setting
device: [0]

# Other settings
work_dir: "./exps/smartfall_har/mobile_falldet"
model_saved_name: "mobile_fall_detector"
print_log: true
phase: "train"
num_worker: 4  # Increased for faster data loading
seed: 2
log_interval: 10
include_val: true