  model: "Models.moveLoss.EnhancedFallDetectionModel"

  # Model arguments
  model_args:
      seq_length: 128          
      num_channels: 3       
      num_filters: 64

  # Dataset configuration
  dataset: "smartfallmm"
  subjects:
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 43
    - 44
    - 45
    - 46

  dataset_args:
    root_dir: "data/smartfallmm"
    age_groups:
      - "young"
      - "old"
    modalities:
      - "accelerometer"
    sensors:
      accelerometer:
        - "phone"
        - "watch"
    mode: "avg_pool"
    max_length: 128
    task: "fd"            
    use_smv: false        
  feeder: "Feeder.Make_Dataset.UTD_mm"
  train_feeder_args:
    batch_size: 16

  val_feeder_args:
    batch_size: 16

  test_feeder_args:
    batch_size: 16

  # Training parameters
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16
  num_epoch: 150
  start_epoch: 0

  # Optimizer settings
  optimizer: "adamw"
  base_lr: 0.0001
  weight_decay: 0.0004

  # Loss function
  loss: "torch.nn.BCEWithLogitsLoss"
  loss_args: {}

  # Device setting
  device: [0]

  # System settings
  include_val: True
  seed: 2
  log_interval: 10
  work_dir: "exps/smartfall_har/fall_detection_modelStop"
  print_log: True
  phase: "train"
  num_worker: 0
  result_file: results2
