# Model configuration
model: Models.enhanced_teacher.EnhancedTeacherModel
dataset: 'smartfallmm'
subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

model_args:
  device: 'cuda'
  mocap_frames: 128
  acc_frames: 128
  num_joints: 32
  in_chans: 3
  num_patch: 8
  acc_coords: 4
  spatial_embed: 128
  sdepth: 4
  adepth: 4
  tdepth: 6
  num_heads: 8
  mlp_ratio: 4
  qkv_bias: True
  qk_scale: null
  op_type: 'all'
  embed_type: 'lin'
  drop_rate: 0.3
  attn_drop_rate: 0.3
  drop_path_rate: 0.3
  norm_layer: null
  num_classes: 2

# Loss function
loss: 'torch.nn.CrossEntropyLoss'
loss_args: {}

# Dataset arguments
dataset_args: 
  mode: 'avg_pool'
  max_length: 128
  task: 'fd'
  modalities: ['skeleton', 'accelerometer']
  age_group: ['young','old']
  sensors: ['watch']

# Training parameters
batch_size: 16
test_batch_size: 16
val_batch_size: 16 
num_epoch: 120

# Data loader configuration
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  batch_size: 16

val_feeder_args:
  batch_size: 16

test_feeder_args:
  batch_size: 16

seed: 2
optimizer: 'sgd'
base_lr: 0.0025
weight_decay: 0.0004

# Additional settings
work_dir: 'exps/smartfall_har/teacher/enhanced'
model_saved_name: 'enhanced_transformer'
print_log: True
phase: 'train'
num_worker: 0
result_file: null
