# Model configuration
model: Models.s2.EnhancedStudentModel
dataset: smartfallmm

subjects:
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 43
  - 44
  - 45
  - 46

model_args:
  acc_coords: 4
  seq_length: 128
  num_virtual_joints: 32
  spatial_embed: 128
  num_heads: 8
  depth: 6
  mlp_ratio: 4
  num_classes: 2
  dropout: 0.1

# Dataset arguments
dataset_args:
  mode: 'avg_pool'
  max_length: 128
  task: 'fd'             # Fall detection task
  modalities: ['accelerometer']  # Only accelerometer for student
  age_group: ['young', 'old']
  sensors: ['watch']

# Training parameters
batch_size: 32
test_batch_size: 32
val_batch_size: 32
num_epoch: 300
start_epoch: 0

feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 32
val_feeder_args:
  batch_size: 32
test_feeder_args:
  batch_size: 32

# Optimization parameters
seed: 42
optimizer: 'adamw'  # AdamW for better generalization
base_lr: 0.0001
weight_decay: 0.0004

# Additional settings
work_dir: 'exps/smartfall_har/student'
model_saved_name: 'fall_detector_student'
print_log: True
phase: 'train'
num_worker: 4

# Device setting
device: [0]