#Model
model: Models.transformer.TransModel
# file name of weights 
#work_dir: exps/UTD_woKD/acc_modal
#model_saved_name : student_sliding
dataset: smartfallmm

#subjects: [2,3,4,5,6,7,15,16,17,18,19,21,23,22,26]
# test_subjects: [18]
#subjects: [1,2, 3, 4, 5,7,8,9, 10,11, 12,13,14,15, 16, 17, 18,47, 19,22,23]
subjects: [1,2, 3, 4, 5,7,8,9, 10,11, 12,13,14,15, 16, 17, 18,47,19,22,23]

model_args:
  num_layers : 2
  norm_first : True
  embed_dim: 32
  activation: relu 
  acc_coords : 4
  num_classes: 8
  acc_frames : 128
  mocap_frames : 128
  num_heads: 2
  # mocap_frames: 50

batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 300

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: sgd