

#Model
model: Models.ef_w_decoder.MMTransformer
# model : Models.model_crossview_fusion.ActRecogTransformer
# model_saved_name : tokenfusion_AdamW_avgpool
# work_dir: exps/UTD_woKD/with_AdamW
dataset: 'smartfallmm'


model_args:
  mocap_frames: 32
  num_joints: 32
  in_chans: 3 
  spatial_embed: 32 
  num_classes: 2
  sdepth: 4
  tdepth: 4
  acc_frames : 32
  # num_joints : 20
  # num_classes : 27
  # spatial_embed : 32
  # adepth : 2
  # sdepth : 2
  # num_heads : 4
  # mocap_frames: 32
  num_patch: 8
  acc_coords: 3
  # drop_path_rate: 0.4
  # drop_rate: 0.4
  # attn_drop_rate: 0.4



# loss_args 
loss_args:
  beta: 0.2


#optim
weight_decay: 0.0004
# base_lr: 0.001


# training
#changeable
batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 250

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: adam
