# Model Configuration
model: Models.transog.TransModel
dataset: smartfallmm

# Subjects for Fall Detection
subjects:
  - 29
  - 30
  - 31
  - 32
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46

# Model Arguments
model_args:
  acc_frames: 128           # Sequence length for accelerometer data
  acc_coords: 4             # Channels (x, y, z, svm)
  num_classes: 2            # Binary classification (fall vs no fall)
  num_heads: 2              # Transformer heads
  num_layers: 2             # Transformer layers
  embed_dim: 128             # Embedding dimension
  activation: relu          # Activation function

# Dataset Arguments
dataset_args:
  mode: 'avg_pool'
  max_length: 128
  task: 'fd'                # Task: Fall Detection
  modalities: ['skeleton','accelerometer']
  age_group: ['young', 'old']
  sensors: ['watch']        # Sensors: Phone

# Training Configuration
batch_size: 16
test_batch_size: 16
val_batch_size: 16
num_epoch: 300

# Data Loader Configuration
feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 16
val_feeder_args:
  batch_size: 16
test_feeder_args:
  batch_size: 16

# Optimization Parameters
seed: 2
optimizer: sgd
base_lr: 0.001
weight_decay: 0.0004


# Additional Settings
include_val: True

scheduler: None
scheduler_args: '{}'
log_interval: 10
print_log: True
phase: 'train'

# Work Directory
work_dir: 'exps/smartfall_har/transformer'
model_saved_name: 'transmodel_fd'

