# Basic configuration
model: "Models.watchTrans.TransWatchModel"
dataset: "smartfallmm"

# Model parameters
model_args:
  input_channels: 4     # x, y, z, smv
  d_model: 64
  nhead: 4
  num_layers: 2
  dim_feedforward: 128
  dropout: 0.3

# Dataset arguments
dataset_args:
  mode: "sliding_window"
  max_length: 128
  task: "fd"
  modalities: ["accelerometer"]
  age_group: ["young"]
  sensors: ["watch"]

# Subject IDs as a flat list
subjects: [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 44, 45, 46]

# Training parameters
batch_size: 64
test_batch_size: 64
val_batch_size: 64
num_epoch: 150
start_epoch: 0

# Optimizer settings
optimizer: "adamw"
base_lr: 0.001
weight_decay: 0.0004

# Device config
device: [0]

# Feeder settings
feeder: "Feeder.Make_Dataset.UTD_mm"
train_feeder_args:
  batch_size: 64
val_feeder_args:
  batch_size: 64
test_feeder_args:
  batch_size: 64

# Additional training
num_worker: 4
seed: 42
include_val: true
print_log: true
phase: "train"

# Loss function configuration
loss: "torch.nn.BCELoss"
loss_args: {}

# Scheduler settings
scheduler: "cosine"
scheduler_args:
  warmup_epochs: 10
