#Model
model: Models.model_acc_only.ActTransformerAcc
dataset: czu
# file name of weights 

model_args:
  acc_frames : 32
  num_joints : 25 
  num_classes : 22
  acc_embed : 16
  adepth : 4
  num_heads : 4
  acc_coords: 6
  spatial_embed: 32
  drop_path_rate: 0.3
  drop_rate: 0.3
  attn_drop_rate: 0.3

  # mocap_frames: 50


batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 250

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: adam
