teacher_model: Models.ef_w_decoder.MMTransformer
student_model: Models.model_acc_only.ActTransformerAcc
dataset: bmhad
#teacher_weight: exps/berkley_woKD/teacher_woKD/berkley_teacherwoKD.pt

#model_args
teacher_args:
  acc_frames : 50
  num_joints : 31
  num_classes : 11
  spatial_embed : 32
  #acc_embed: 16
  adepth : 2
  sdepth : 2
  num_heads : 4
  mocap_frames: 50
  num_patch: 5
  acc_coords: 3
  drop_path_rate: 0.4
  drop_rate: 0.4

student_args: 
  acc_frames : 50
  num_joints : 31
  num_classes : 11
  #spatial_embed : 64
  acc_embed: 32
  adepth : 2
  #sdepth : 2
  num_heads : 4
  #mocap_frames: 256
  #num_patch: 16
  acc_coords: 3

#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 16
test_batch_size: 16
val_batch_size : 16
num_epoch: 250

#dataloader
feeder: Feeder.Make_Dataset.Bmhad_mm

distill_loss: loss.SemanticLoss
distill_args: 
  T : 2
  alpha: 0.7

student_loss: loss.BCE


train_feeder_args:
  # npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 16

val_feeder_args:
  # npz_file: data/UTD_MAAD/utd_val_op_mf50_norm.npz
  batch_size: 16

test_feeder_args: 
  # npz_file: data/UTD_MAAD/utd_test_op_mf50_norm.npz
  batch_size: 16

seed: 2 
optimizer: sgd