#Model
model: Models.ef_w_decoder.MMTransformer
model_saved_name : no_kd_aug

#model_args
model_args:
  acc_frames : 256
  num_joints : 20
  num_classes : 27
  spatial_embed : 128
  adepth : 4
  sdepth : 4
  num_heads : 8
  mocap_frames: 600
  num_patch: 10


#optim
weight_decay: 0.0004
base_lr: 0.001


# training
batch_size: 8
test_batch_size: 8
val_batch_size : 8
num_epoch: 50

#dataloader
feeder: Feeder.Make_Dataset.UTD_mm

train_feeder_args:
  npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 32

val_feeder_args:
  npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 32

test_feeder_args: 
  npz_file: data/UTD_MAAD/utd_train_op_mf50_norm.npz
  batch_size: 32

seed: 2 
optimizer: Adam
