#Model
model: Models.ef_w_decoder.MMTransformer
# model_saved_name : berkley_convtransformer_slide10
# work_dir: exps/bhmad_woKD/MMNorm
# model : Models.model_crossview_fusion.ActRecogTransformer
dataset: 'bmhad'


#model_args
model_args:
  acc_frames : 50
  num_joints : 31
  num_classes : 11
  spatial_embed : 32
  #acc_embed: 16
  adepth : 2
  sdepth : 2
  num_heads : 4
  mocap_frames: 50
  num_patch: 5
  acc_coords: 3
  drop_path_rate: 0.4
  drop_rate: 0.4
  attn_drop_rate: 0.4


#optim
weight_decay: 0.004
# base_lr: 0.0025


# training
batch_size: 8
test_batch_size: 8
val_batch_size : 8
num_epoch: 50 

#dataloader
feeder: Feeder.Make_Dataset.Bmhad_mm

train_feeder_args:
  batch_size: 8

val_feeder_args:
  batch_size: 8

test_feeder_args: 
  batch_size: 8

seed: 2 
optimizer: sgd
