teacher_model: Models.t3.EnhancedTeacherModel
student_model: Models.s3.EnhancedStudentModel
dataset: smartfallmm

# List of subjects for training and testing
subjects:
  - 29
  - 30
  - 31
  - 32
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46

# Teacher model arguments
teacher_args:
  num_joints: 32
  in_chans: 3
  acc_coords: 4
  spatial_embed: 256
  num_heads: 8
  depth: 6
  mlp_ratio: 4
  num_classes: 2
  dropout: 0.1

# Student model arguments
student_args:
  acc_coords: 4
  seq_length: 128
  num_virtual_joints: 32
  spatial_embed: 32
  num_heads: 8
  depth: 6
  mlp_ratio: 4
  num_classes: 2
  dropout: 0.5

dataset_args:
  mode: 'avg_pool'
  max_length: 128
  task: 'fd'               # Fall detection task
  modalities: ['skeleton', 'accelerometer']
  age_group: ['young', 'old']
  sensors: ['watch']

# Optimization parameters
batch_size: 32
test_batch_size: 32
val_batch_size: 32
num_epoch: 300

# Dataloader
feeder: Feeder.Make_Dataset.UTD_mm

distill_loss: utils.loss.DistillationLoss
distill_args:
  T: 2
  alpha: 0.7
  feature_weight: 0.1

student_loss: torch.nn.CrossEntropyLoss
loss_args: {}
train_feeder_args:
  batch_size: 32

val_feeder_args:
  batch_size: 32  

test_feeder_args:
  batch_size: 32

seed: 42
optimizer: adamw
base_lr: 0.00001

